# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lob', '0004_auto_20200507_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='board_id',
        ),
    ]
