# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lob', '0005_remove_notice_board_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=200)),
                ('board_contents', models.TextField()),
                ('board_writer', models.CharField(max_length=200)),
                ('board_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_contents', models.TextField()),
                ('comment_writer', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField(verbose_name='date published')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lob.Board')),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
